import java.sql.*;
import Internship.oracle_Bank_System.bank.UI;
public class Atm extends  UI{
    public static void main(String[] args) {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
        }catch(Exception e){}

        try{
            Connection connection=DriverManager.getConnection(url,userName,password);
            Statement statement=connection.createStatement();
            String query="CREATE TABLE atm_details("+
                    "sr_no NUMBER(3) GENERATED BY DEFAULT ON NULL AS IDENTITY,"+
                    "acc_number VARCHAR(15),"+
                    "mob_number VARCHAR(10),"+
                    "atm_number VARCHAR(16),"+
                    "m_pin VARCHAR(4) DEFAULT'0000',"+
                    "freeze_details VARCHAR(3) DEFAULT 'no',"+
                    "date_time VARCHAR(20),"+
                    "CONSTRAINT atm_details PRIMARY KEY(sr_no))";
            //account number is foreign key REFERENCES to account_details acc_number
            statement.executeUpdate(query);
        }catch(Exception e){
            e.getMessage();
        }
    }
}
