import java.sql.*;
import Internship.oracle_Bank_System.bank.UI;
public class Transaction extends UI {

    public static void main(String[] args) {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
        }catch(Exception e){}

        try{
            Connection connection=DriverManager.getConnection(url,userName,password);
            Statement statement=connection.createStatement();
            String query="CREATE TABLE transaction("+
                    "sr_no NUMBER(3) GENERATED BY DEFAULT ON NULL AS IDENTITY,"+
                    "date_time VARCHAR(20),"+
                    "details VARCHAR(20),"+
                    "debit FLOAT(10) DEFAULT 0,"+
                    "credit FLOAT(10) DEFAULT 0,"+
                    "balance FLOAT(10),"+
                    "fine_charge FLOAT(10) DEFAULT 0,"+
                    "CONSTRAINT transaction_pk PRIMARY KEY(sr_no)"+
                    ")";
            statement.executeUpdate(query);
        }catch(Exception e){
            e.getMessage();
        }
    }
}
